//
//  RecipesPresenter.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecipesPresenter: RecipesPresenterProtocol, RecipesInteractorOutputProtocol {

    weak private var view: RecipesViewProtocol?
    var interactor: RecipesInteractorInputProtocol?
    private let router: RecipesWireframeProtocol

    init(interface: RecipesViewProtocol, interactor: RecipesInteractorInputProtocol?, router: RecipesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
