//
//  RecipesProtocols.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RecipesWireframeProtocol: class {

}
//MARK: Presenter -
protocol RecipesPresenterProtocol: class {

    var interactor: RecipesInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol RecipesInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol RecipesInteractorInputProtocol: class {

    var presenter: RecipesInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol RecipesViewProtocol: class {

    var presenter: RecipesPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
