//
//  NewRecipeViewController.swift
//  VIPER-Recipes
//
//  Created admin on 19.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SnapKit
import CoreData

class NewRecipeViewController: UIViewController, NewRecipeViewProtocol {

	var presenter: NewRecipePresenterProtocol?
    
    let nameTextField = UITextField()
    let pictureImageView = UIImageView(image: UIImage(named: "Icons/picture"))
    
	override func viewDidLoad() {
        super.viewDidLoad()
        let saveButton = UIBarButtonItem(barButtonSystemItem: .save, target: self, action: #selector(saveRecipe))
        let backButton = UIBarButtonItem(barButtonSystemItem: .cancel , target: self, action: #selector(back))
        navigationItem.rightBarButtonItem = saveButton
        navigationItem.leftBarButtonItem = backButton
        view.backgroundColor = .white
        setup()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        pictureImageView.snp.makeConstraints({make in
            make.left.equalTo(20)
            make.top.equalTo(100)
        })
        nameTextField.snp.makeConstraints({ make in
            make.left.equalTo(pictureImageView.snp.right)
            make.top.equalTo(120)
        })
    }
    
    private func setup() {
        
        view.addSubview(nameTextField)
        view.addSubview(pictureImageView)
        nameTextField.placeholder = "Recipe name"
        pictureImageView.addGestureRecognizer(tap)
        pictureImageView.contentMode = .scaleAspectFill
    }
    
    @objc private func didTap() {
        print("click")
    }
    
    @objc private func saveRecipe() {
        let name = nameTextField.text
        DataCoordinator.performBackgroundTask { (context) -> (Void) in
            let obj = Recipe(context: context)
            obj.name = name
            do {
                print(context.hasChanges)
                try context.save()
                print("saved changes")
            } catch {
                print("exception saving in background thread")
            }
        }
    }
    
    @objc private func back() {
        dismiss(animated: true)
    }

}
