//
//  NewRecipeProtocols.swift
//  VIPER-Recipes
//
//  Created admin on 19.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NewRecipeWireframeProtocol: class {

}
//MARK: Presenter -
protocol NewRecipePresenterProtocol: class {

    var interactor: NewRecipeInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol NewRecipeInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol NewRecipeInteractorInputProtocol: class {

    var presenter: NewRecipeInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol NewRecipeViewProtocol: class {

    var presenter: NewRecipePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
