//
//  NewRecipeRouter.swift
//  VIPER-Recipes
//
//  Created admin on 19.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewRecipeRouter: NewRecipeWireframeProtocol {

    weak var viewController: UIViewController?

}
