//
//  GroceryProtocols.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GroceryWireframeProtocol: class {

}
//MARK: Presenter -
protocol GroceryPresenterProtocol: class {

    var interactor: GroceryInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol GroceryInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol GroceryInteractorInputProtocol: class {

    var presenter: GroceryInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol GroceryViewProtocol: class {

    var presenter: GroceryPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
