//
//  SavesProtocols.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SavesWireframeProtocol: class {

}
//MARK: Presenter -
protocol SavesPresenterProtocol: class {

    var interactor: SavesInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SavesInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SavesInteractorInputProtocol: class {

    var presenter: SavesInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SavesViewProtocol: class {

    var presenter: SavesPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}


protocol SavesLocalCellDelegate: class {
    //
}
