//
//  SavesRouter.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SavesRouter: SavesWireframeProtocol {

    weak var viewController: UIViewController?

}
