//
//  SavesPresenter.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SavesPresenter: SavesPresenterProtocol, SavesInteractorOutputProtocol {

    weak private var view: SavesViewProtocol?
    var interactor: SavesInteractorInputProtocol?
    private let router: SavesWireframeProtocol

    init(interface: SavesViewProtocol, interactor: SavesInteractorInputProtocol?, router: SavesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
