//
//  SignUpPresenter.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpPresenter: SignUpPresenterProtocol {

    weak private var view: SignUpViewProtocol?
    var interactor: SignUpInteractorInputProtocol?
    private let router: SignUpWireframeProtocol

    init(interface: SignUpViewProtocol, interactor: SignUpInteractorInputProtocol?, router: SignUpWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func signUp(_ email: UITextField, _ password: UITextField, _ confirmPassword: UITextField) {
        interactor?.signUp(email, password, confirmPassword)
    }
    
    func dismiss() {
        router.dismiss()
    }

}

extension SignUpPresenter: SignUpInteractorOutputProtocol {
    func showError(_ message: String) {
        view?.showError(message)
    }
    
    func onSuccessSignUp() {
        router.dismiss()
    }
}
