//
//  SignUpProtocols.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol SignUpWireframeProtocol: class {
    
    /* ViewController -> Wireframe */
    func dismiss()

}
//MARK: Presenter -
protocol SignUpPresenterProtocol: class {

    var interactor: SignUpInteractorInputProtocol? { get set }
    
    /* ViewController -> Presenter */
    func signUp(_ email: UITextField, _ password: UITextField, _ confirmPassword: UITextField)
    func dismiss()
}

//MARK: Interactor -
protocol SignUpInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func showError(_ message: String)
    func onSuccessSignUp()
}

protocol SignUpInteractorInputProtocol: class {

    var presenter: SignUpInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    
    func signUp(_ email: UITextField, _ password: UITextField, _ confirmPassword: UITextField)
}

//MARK: View -
protocol SignUpViewProtocol: class {

    var presenter: SignUpPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func showError(_ message: String)
}

protocol SignUpViewDelegate: class {
    func signUpButtonClicked()
    func backButtonClicked()
    func showError(_ message: String)
}
