//
//  SignUpViewController.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpViewController: UIViewController, SignUpViewProtocol {

	var presenter: SignUpPresenterProtocol?
	var ui: SignUpView? = nil
    
    override func loadView() {
        super.loadView()
        ui = SignUpView()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        ui?.delegate = self
        view = ui
    }

}

extension SignUpViewController: SignUpViewDelegate {
    func signUpButtonClicked() {
        presenter?.signUp(ui!.emailTextField, ui!.passwordTextField, ui!.confirmPasswordTextField)
    }
    
    func backButtonClicked() {
        presenter?.dismiss()
    }
    
    func showError(_ message: String) {
        DispatchQueue.main.async {
            self.ui?.errorLabel.text = message
            self.ui?.errorLabel.alpha = 1
        }
    }
    
    
}
