//
//  LogInInteractor.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Firebase

class LogInInteractor: LogInInteractorInputProtocol {

    weak var presenter: LogInInteractorOutputProtocol?
    
    func signIn(_ email: UITextField, _ password: UITextField) {
        // Validate the fields
        let error = Utilities.validateFields(email, password)
        
        if error != nil {
            // There's somethins wrong with the fields
            // show error message
            presenter?.showError(error!)
        } else {
            
            // Create cleaned versions of the data
            let email = email.text!.trimmingCharacters(in: .whitespacesAndNewlines)
            let password = password.text!.trimmingCharacters(in: .whitespacesAndNewlines)
            
            // SignIn the user
            Auth.auth().signIn(withEmail: email, password: password) { (result, err) in
                if err != nil {
                    // There was an error creating the user
                    self.presenter?.showError("\(err!.localizedDescription)")
                }
                else {
                    let defaults = UserDefaults.standard
                    defaults.set(result?.user.uid, forKey: "UserUID")
                    self.presenter?.onSuccessAuth()
                }
            }
        }  
    }
}
