//
//  LogInRouter.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum Navigation {
    case signUp
    case forgotPassword
    case successAuth
}

class LogInRouter: LogInWireframeProtocol {

    weak var viewController: UIViewController?

    func navigate(with type: Navigation) {
        switch type {
        case .signUp:
            DispatchQueue.main.async {
                let vc = SignUpConfigurator.createModule()
                vc.modalPresentationStyle = .overFullScreen
                self.viewController?.present(vc, animated: true, completion: nil)
            }
        case .forgotPassword:
            return
        case .successAuth:
            DispatchQueue.main.async {
                let vc = MainTabBarController()
                vc.modalPresentationStyle = .overFullScreen
                self.viewController?.present(vc, animated: true, completion: nil)
            }
        }
    }
}
