//
//  LogInViewController.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LogInViewController: UIViewController {

	var presenter: LogInPresenterProtocol?
    var ui: LogInView? = nil
    
    override func loadView() {
        super.loadView()
        ui = LogInView()
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        ui?.delegate = self
        view = ui
        checkUserUID()
    }
    
    /// Check user uid in UserDefaults
    private func checkUserUID() {
        let defaults = UserDefaults.standard
        let uid = defaults.string(forKey: "UserUID")
        
        if uid != nil {
            presenter?.signIn()
        }
    }

}

extension LogInViewController: LogInViewDelegate {
    func signInButtonClicked() {
        presenter?.signIn(ui!.emailTextField, ui!.passwordTextField)
    }
    
    func signUpButtonClicked() {
        presenter?.signUp()
    }
    
    func showError(_ message: String) {
        DispatchQueue.main.async {
            self.ui?.errorLabel.text = message
            self.ui?.errorLabel.alpha = 1
        }
    }
}

extension LogInViewController: LogInViewProtocol {

}
