//
//  MoreProtocols.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MoreWireframeProtocol: class {

}
//MARK: Presenter -
protocol MorePresenterProtocol: class {

    var interactor: MoreInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MoreInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MoreInteractorInputProtocol: class {

    var presenter: MoreInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MoreViewProtocol: class {

    var presenter: MorePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
