//
//  MorePresenter.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MorePresenter: MorePresenterProtocol, MoreInteractorOutputProtocol {

    weak private var view: MoreViewProtocol?
    var interactor: MoreInteractorInputProtocol?
    private let router: MoreWireframeProtocol

    init(interface: MoreViewProtocol, interactor: MoreInteractorInputProtocol?, router: MoreWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
