//
//  MoreViewController.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Firebase

class MoreViewController: UIViewController, MoreViewProtocol {

	var presenter: MorePresenterProtocol?

    var ui: MoreView? = nil
    
    
    
    override func loadView() {
        super.loadView()
        ui = MoreView()
       
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        ui?.delegate = self
        view = ui
        
        let logoutButton = UIBarButtonItem(barButtonSystemItem: .close, target: self, action: #selector(logout))
        navigationItem.rightBarButtonItem = logoutButton
    }
    
    @objc private func logout() {
        
        let logoutAction = UIAlertAction(title: "EXIT", style: .destructive, handler: { action in
            
            do {
                try Auth.auth().signOut()
            } catch {
                print(error.localizedDescription)
            }
            
            let defaults = UserDefaults.standard
            defaults.removeObject(forKey: "UserUID")
            
            let vc = LoginWireframe.makeViewController(delegate: nil)
            vc.modalPresentationStyle = .overFullScreen
            self.present(vc, animated: true, completion: nil)
            
        })
        
        let cancelAction = UIAlertAction(title: "back", style: .cancel, handler: nil)
        
        AlertService.showAlert(style: .actionSheet, title: "Logout", message: "Do you realy want to exit?", actions: [logoutAction, cancelAction], completion: nil)
    
    }

}

extension MoreViewController: MoreViewDelegate {
    
}
