//
//  MoreViewController.swift
//  VIPER-Recipes
//
//  Created admin on 18.02.2020.
//  Copyright © 2020 Rinat Kutuev. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoreViewController: UIViewController, MoreViewProtocol {

	var presenter: MorePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
